version: '3.8'
services:
  postgres_db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    container_name: postgres_db
    networks:
      some_network:
        aliases:
          - database
          - localhost
  web:
    build: .
    command: gunicorn WEBPROYECT.wsgi:application -b :8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    links:
      - postgres_db:postgres_db
    container_name: web
    networks:
      - some_network
networks:
  some_network: